messaging/__init__.py
messaging/impl_msgq.cc
messaging/impl_msgq.hpp
messaging/impl_zmq.cc
messaging/impl_zmq.hpp
messaging/messaging.cc
messaging/messaging.hpp
messaging/messaging.pxd
messaging/messaging_pyx.pyx
messaging/msgq.cc
messaging/tests/test_poller.py

Implementation of https://github.com/commaai/cereal/pull/15 with exception handling upstream.

Implement error handling and exceptions

---

car.capnp

add honda ecus

---

car.capnp

continuation of https://github.com/commaai/cereal/pull/7

Add blindspot cereal values

---

README.md
messaging/__init__.py

`new_message()` includes service and optional list size parameter to create a new message in just 1 line.
Old code:
```python
pm = messaging.PubMaster(['carControl'])
cc_send = messaging.new_message()
cc_send.init('carControl')
cc_send.valid = CS.canValid
cc_send.carControl = CC
pm.send('carControl', cc_send)
```
New code:
```python
pm = messaging.PubMaster(['carControl'])
cc_send = messaging.new_message('carControl')
cc_send.valid = CS.canValid
cc_send.carControl = CC
pm.send('carControl', cc_send)
```

Create and init message in one line with `new_message` in messaging 

---

car.capnp

If there is something in the way. Create alert for User to know why it can not lane change currently

Add the laneChangeBlocked Event

---

SConscript
messaging/messaging.hpp
messaging/socketmaster.cc

reusing an kj::array to do alignment related copy.
poll() will validate the incoming message,and return an event array
pollRaw() and receive() will not read the event. caller must call getEvent to parse and get the event.
check if message is "alive" when the optional parameter "alive" is set to true.but I have no idea where to use this flag.so I keep the message processing mode remains the same as before.: commaai/openpilot#1476
@pd0wm @adeebshihadeh

Sub pub master

---

SConscript

related to: https://github.com/commaai/openpilot-apks/pull/58

move socketmaster.cc to messaging

---

SConscript
messaging/msgq.cc

It seems to me like messaging/socketmaster.cc was in the wrong place in the build script.

fix mac build

---

messaging/msgq.cc
messaging/tests/test_messaging.py

https://github.com/commaai/cereal/issues/41

fix the isssue 41

---

car.capnp

Parametrize startingBrakeRate

---

car.capnp

Adding breakpoints to INDI lateral tuning

Adding breakpoints to INDI lateral tuning

---

car.capnp

support setting max steer angle in car params

add maxSteerAngle to car.capnp

---

messaging/__init__.py
messaging/impl_msgq.cc
messaging/impl_msgq.hpp
messaging/impl_zmq.cc
messaging/impl_zmq.hpp
messaging/messaging.hpp
messaging/messaging.pxd
messaging/messaging_pyx.pyx
messaging/msgq.cc
messaging/msgq.hpp
messaging/socketmaster.cc
services.py

- extra getters
- bugfix in allAliveAndValid
- check for PubMaster to see if all readers are updated

some fixes and small changes for locationd in c++

---

messaging/tests/test_services.py
services.py

These might be out of date, I heard you're switching to 22 for ssh? Let me know if these are incorrect and I can update/close.
This would help me and probably others from adding a new struct here that accidentally overlapped a reserved port

Automatically generate service ports

---

services.py

So we can include services.h from C++17 (PlotJuggler)

Use C89-style struct syntax for services header

---

car.capnp

Displayed when joystick debug param is set before ignition

Permanent joystick debug alert 

---

log.capnp

Change fault name to match Panda refactored code

Rename panda fault #21

---

log.capnp

Change name for RP in log.capnp

change name for Red Panda

---

visionipc/visionbuf_ion.cc

relating to https://github.com/commaai/openpilot/pull/22054

VisionBuf: retry ioctls while errno == EINTR

---

SConstruct
visionipc/visionbuf.cc
visionipc/visionbuf_cl.cc

See https://github.com/commaai/openpilot/pull/22756

fix wshadow errors

---

log.capnp

Add roll to liveparameters

---

car.capnp

Signed-off-by: Jafar Al-Gharaibeh <to.jafar@gmail.com>

Add event for lkas disabled

---

car.capnp
log.capnp

For https://github.com/commaai/openpilot/pull/23538 🙂

Add unsafeMode to carParams

---

log.capnp

needed for panda deepsleep mode

Panda deep sleep mode: add new interrupt fault

---

car.capnp

For openpilot PR https://github.com/commaai/openpilot/pull/23859

Fields for active actuators

---

car.capnp
log.capnp

rename unsafeMode to alternativeExperience

---

car.capnp
log.capnp

For panda PR: https://github.com/commaai/panda/pull/910

Make safetyParam unsigned

---

log.capnp
services.py

Add GnssMeasurements msg to be used for laikad -> locationd

Add GnssMeasurements

---

log.capnp

Combination of constellationId and svId results in the unique satellite.
Also add other satellite constellations.

Change gnssid to constellationid

---

log.capnp

VelocityECEF will be used to initialize kalman filter

Add velocity to gnssmeasurements

---

log.capnp

See https://github.com/commaai/openpilot/pull/23158

Navigation speed limit

---

visionipc/visionbuf.cc
visionipc/visionbuf.h
visionipc/visionipc.pxd
visionipc/visionipc_client.cc
visionipc/visionipc_pyx.pyx
visionipc/visionipc_server.cc
visionipc/visionipc_server.h

needed for https://github.com/commaai/openpilot/pull/24519

use nv12 for visionipc

---

log.capnp
services.py

This reverts commit 96cbed052ab1d69ea15da94dc2b882d59a786347.

Revert driverStateV2

---

log.capnp

The bearing degree can also be calculated in locationd so we don't have to sent it

Remove bearingDeg from Gnssmeasurements

---

car.capnp

Unused for quite a while, we'll use this to have controlsd tell carcontroller when to press the resume button

Rename override to resume in CarControl.CruiseControl

---

log.capnp
services.py

This reverts commit ff49c8e126ea04889af13d690ceaf520ce7084d2.

driverStateV2

---

.github/workflows/tests.yml

* Added DOCKER_REGISTRY to env variables.
* Updated checkout to v3.

CI: checkout@v3 & DOCKER_REGISTRY env variable

---

log.capnp

Panda health: names and mixup fix

---

log.capnp
messaging/tests/test_services.py
services.py

split up sensorEvents and give every sensor its own service

Sensor events splitup

---

log.capnp
services.py

mark sensorEvents deprecated

---

car.capnp

we use this for Ford fingerprinting now

make shiftByWire non-Honda specific

---

log.capnp

related to https://github.com/commaai/panda/pull/1082

add CAN-FD non-ISO mode

---

car.capnp

carControl->cruiseControl: add override bool

---

messaging/msgq.cc
messaging/msgq.h

plotjuggler mac fails to build in ci due to this warning
https://github.com/commaai/PlotJuggler/actions/runs/3578341842/jobs/6018897217#step:5:59

fix set but unused warning

---

car.capnp
log.capnp

- https://github.com/commaai/openpilot/pull/26236

add curvature steer control type

---

log.capnp

better names and prepare for laikad switch

gnssMeasurement Renaming

---

car.capnp

OP PR: https://github.com/commaai/openpilot/pull/27345

Log if data-collection for each carFw

---

car.capnp

see https://github.com/commaai/openpilot/pull/28204

Subaru: rename legacy preglobal

---

car.capnp

for https://github.com/commaai/openpilot/pull/28612

Ecu: add electronic parking brake

---

car.capnp

Related to https://github.com/commaai/cereal/pull/481
For https://github.com/commaai/openpilot/pull/28613
this is different than combinationMeter and hud

Ecu: add telematics

---

messaging/__init__.py

Assume frequency is invalid until it isn't. Normally doesn't make a difference, but it did in https://github.com/commaai/openpilot/issues/28644.

SubMaster: fix recv_dts initial state

---

messaging/__init__.py
messaging/messaging_pyx.pyx

SIMULATION flag might be set after importing the module.

SubMaster: replace SIMULATION constant with property

---

log.capnp

Full list: https://docs.mapbox.com/api/navigation/directions/#lane-object

NavInstruction.Direction: add slight turns

---

services.py

fix clang 14 / ubuntu 22 build

services: add missing import

---

visionipc/visionipc_client.cc
visionipc/visionipc_client.h
visionipc/visionipc_server.cc
visionipc/visionipc_server.h

1. move duplicate code into helper function `get_ipc_path`
2. cleanup includes

visionipc: new helper function  `get_ipc_path`

---

visionipc/visionipc_server.cc

https://github.com/commaai/openpilot/pull/31378

move vipc to a prefix folder

---

.github/workflows/tests.yml

Can pull cache on mine (https://github.com/bongbui321/cereal/actions/runs/8015514916/job/21895802702)
I'll put up another PR for the scons cache if you like

CI: enable docker cache

---

messaging/__init__.py

this is already the case for cpp api

Submaster (python): set alive when first seen for simulation=1
