commaai/msgq

- car.capnp
A follow up PR for openpilot and opendbc (for Honda maybe with a refactor for Toyota) will be coming soon.
> Add lane departure warning to visual hud alerts

- car.capnp
This is the first in a series of PRs to upstream the Volkswagen, Audi, SEAT, and Škoda community port. However, almost all of these changes could be useful for other manufacturer ports.
Additional PRs will be opened for OpenDBC, Panda safety, and OP updates in due course. I am filing this one first to avoid breaking your upload and ingest pipeline. I will make the corresponding changes in our port if and when you merge this PR.
**Add generic (manufacturer-independent) cruise-control button events in support of enhanced steering wheel or third stalk ACC control.**
This change is required because our button semantics are different. Our cars DO NOT have the traditional overloaded res/accel or set/coast buttons; the Res and Set buttons behave exactly as labeled whether momentarily pressed or …
> Add fields and states required for robust Volkswagen safety compliance

- azure-pipelines.yml
- messaging/msgq.cc
- messaging/msgq.hpp
- messaging/tests/test_poller.py
First off, remove randomness unless there's a real justification for it. In general, unless you absolutely need it, randomness shouldn't be used.
Secondly, with uids being pids, I think the signalling solution is obvious. The polling process can sleep until the publishing process decides it's time to wake it up. I don't know the nuance here, but usleep can be exited by EINTR, though I think the signal handler might have to be configured to do that.
You could get more fine grained with the poll, where the subscriber says if it's blocked on a given socket to avoid spurious wakeups (right now it wakes on all subscribed sockets), but this is a perf optimization for later and maybe not needed at all.
Right now this segfaults with python demo.py, and I don't know why. In general, this software …
> Switch from polling on FIFOs to signal

- car.capnp
The community Volkswagen port is developing support for older Volkswagen, Audi, SEAT and Škoda vehicles. We now have a 2009 Volkswagen Passat R36 up and running successfully in a test branch.
https://my.comma.ai/useradmin/explorer?route=d12cd943127f267b%7C2019-12-29--15-09-02
Their networking concept is a first cousin of MQB, similar enough that we can share one reasonably clean OP port, but different enough to justify a different Panda safety with different regression tests.
Cars this will eventually support:
PQ35: https://en.wikipedia.org/wiki/Volkswagen_Group_A_platform#PQ35_(A5)
PQ46: https://en.wikipedia.org/wiki/Volkswagen_Group_B_platform#PQ46_(A6) (includes NMS)
The safety code will be upstreamed when completed. I expect the OP port to reach upstreamable quality at some point, but …
> Reserve safety ID 21 for VAG PQ35/PQ46

- car.capnp
Allow auto-detection of some important params in preparation for decent VW fingerprinting. These are things we need to discover up-front in get_params() and preserve for later use.
- Add Enum for installed network location, so we can handle folks wired to the camera (R242) vs the gateway (J533). I know Comma likes standard camera integration, but gateway integrations are a popular, growing, and essential "fact on the ground". All we need is a CarParams flag so that when we need to, we can relocate one (1) CarState signal and retarget one (1) CarController can_sends.
- Add an electric vehicle variant to the transmission type Enum. Turns out for true EVs (not hybrids) we have to learn the gearshift lever position from an EV-specific signal.
> Additional car params auto-detection in support of VW

- service_list.yaml
Minor change, but the documentation in service_list.yaml has been tremendously helpful in figuring out which process uses which service, so I updated it to reflect recent changes in openpilot.
> Update service documentation in service_list.yaml

- messaging/messaging.cc
Since currently `MSGQ` is not supported on MacOS, due to absence of `/dev/shm` shared memory filesystem, this commit proposes automatic usage of ZMQ backend on MacOS, without the need to specify an environmental variable.
> Use ZMQ on MacOS

- messaging/impl_msgq.cc
- messaging/msgq.cc
While playing with openpilot tools on Mac (concretely unlogger.py) there was a silent failure caused by absence of `/dev/shm` and resulting segfault due to accessing uninitialized memory in `msgq_init_publisher`.
This caused me to lose some time trying to debug this - hopefully making the failure explicit saves someone time in the future.
> Fix potential segfault in MSGQPubSocket::connect

- messaging/tests/test_messaging.py
- messaging/tests/test_pub_sub_master.py
In preparation of the SubMaster refactor. Once the refactor's done, these python tests should moslty cover the C++ implementation, since all the python stuff will just be a wrapper. The Pub/SubMaster tests should also cover the lower level pub/sub functions, but those should also get their own tests at some point.
> Messaging unit tests

- messaging/__init__.py
This fixes high CPU usage in processes like dmonitoringd which should run at 10hz driven by the driverState packet, but it's main loop runs at 100hz because it subscribes to carState. Blocking on `driverState` reduces dmonitoringd's CPU usage from 6% to 2%.
> allow prioritization of services in SubMaster

- messaging/messaging_pyx.pyx
- messaging/tests/test_poller.py
Using string for send introduced a significant conversion overhead for large messages. For instance, for the below example based on demo.py I have observed a 2-4x speedup.
```
import time
import sys
import os
import cereal
from cereal import messaging
from cereal.messaging import Context, SubSocket, PubSocket, Poller
bts = ("a"*1280*720*3*4).encode("ascii")
MSGS = 1000
if __name__ == "__main__":
c = Context()
sub_sock = SubSocket()
pub_sock = PubSocket()
sub_sock.connect(c, "controlsState")
pub_sock.connect(c, "controlsState")
poller = Poller()
poller.registerSocket(sub_sock)
t = time.time()
for i in range(int(MSGS)):
pub_sock.send(bts)
for s in poller.poll(100):
dat = s.receive()
dt = time.time() - t
print("%.1f msg/s" % (MSGS / dt))
```
> Switch send to using bytes.

- car.capnp
Added minSpeedCan to CarParams to parametrize MIN_CAN_SPEED to car interfaces in OpenPilot.
> Added minSpeedCan to CarParams

- car.capnp
Added stoppingBrakeRate to CarParams to parametrize STOPPING_BRAKE_RATE to car interfaces in OpenPilot.
> Added stoppingBrakeRate to CarParams

- log.capnp
Extend params value to take either Text or Data. This is to allow something like "PandaFirmware" to be processed correctly. According to capnp spec, Text could only be an UTF-8 string, PandaFirmware is evidently a pure binary (as decoded by the web ui):
```
( key = "PandaFirmware",
value = "\x11\x01[\x16|GSe\xd5\x1a+\x94\xff\\f|" ),
```
This is causing logreader.py to fail processing rlog:
```
root@localhost:/data/openpilot$ python tools/lib/logreader.py /tmp/xxx_2021-01-04--21-40-41--0--rlog
Traceback (most recent call last):
File "tools/lib/logreader.py", line 147, in <module>
print(msg)
File "capnp/lib/capnp.pyx", line 1091, in capnp.lib.capnp._DynamicStructReader.str
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 30118: invalid continuation byte
```
Not only …
> Change InitData.params[].value to take Data instead of Text, part 1 of 2

- car.capnp
Don't understand rear steer ratio from the description: `with respect to front steer ratio` means this value is relative to front_sR, or relative to steering wheel angle.
> Improve comments on CarParams from manual

- messaging/messaging.h
- messaging/socketmaster.cc
1. Reader is always valid.
2. Delay initializing MessageContext to prevent it has not been initialized before static SubMaster,which will cause an assert at:
https://github.com/commaai/cereal/blob/bab2f2b95e38da4c968efc31369163056e938b30/messaging/impl_msgq.cc#L73
> C++ SubMaster: make readers always valid

- car.capnp
For VW MQB and PQ, we can support cars that don't have factory Lane Assist. However, as of commaai/openpilot#20742 (enforcement of checks[] for every signal we look at) we need to check if it's there before trying to proxy its signals.
I propose a new carParams Boolean `enableStockCamera`. This Boolean is intended to operate just like `enableBsm`.
There already exists a Boolean `enableCamera`, but it has a different and deeper meaning in the guts of controlsd.
> Add stock LKAS/LDW camera detection flag

- visionipc/visionbuf.h
- visionipc/visionbuf_ion.cc
- visionipc/visionipc_server.cc
https://lwn.net/Articles/480055/ suggest `ION_IOC_FREE` is only necessary after `ION_IOC_SHARE` but this doesn't seem to be the case.
> Always free ION buffer

- car.capnp
Prep for upstream of Tunder's 5th gen RAM 1500 port, which may also support the new 4th gen Jeep Wagoneer and Grand Wagoneer. Messaging and operation looks to be fully distinct from the older Chrysler/FCA platforms.
> Stellantis: Allocate safety mode ID

- services.py
@pd0wm last thing that relies on this is "LTE emm-detached" detection. do we still need that? maybe we should make it a cloudlog instead?
> remove androidLog from qlogs

- log.capnp
Currently when we run offline `parmasd`, the covariances are always initialized to incorrect default values. Due to this, we cannot currently recreate online failures accurately. 
I did not create a new `Measurement` struct like in `liveLocationKalman` as some of the variables are expected in degrees and I wanted to avoid needless conversions.
> Add STD to the liveParameter message to enable more accurate offline runs

- car.capnp
- log.capnp
For openpilot PR https://github.com/commaai/openpilot/pull/23859
> Fields for active actuators

- car.capnp
Reserve safety mode identifier for the FAW Hongqi HS5.
> FAW: Add safety mode

- messaging/__init__.py
Fixed bug where openpilot doesn't engage because it issue a  **"Low Communication Rate between Processes"** warning on the Carla simulation. 
This behavior happens because the messaging library doesn't set the `self.freq_ok[s]` to True for the `msgs` on the `update_msgs ` method when it is a simulation.
> Fixed cereal bug for simulation in Carla

- car.capnp
A Float32 "fuelGauge" represents the fuel gauge value from
0.0 to 1.0. It should be generic enough for whatever power
source we call fuel be it gas, electric or something else.
> add fuelGauge to CarState

- log.capnp
Adds the actual curvature and curvature rate that comes out of "get_lag_adjusted_curvature()" and is fed into and used by the lateral controllers. The fields are referred to in controlsd (and the parameter name in update() in the lateral controllers) as desired_curvature and desired_curvature_rate.
Added the fields to ControlsState.
This PR goes together with OP PR: https://github.com/commaai/openpilot/pull/24505
**Background**
While attempting to diagnose unusual tuning behavior in GM Trucks, I had a need to analyze the curvature, and discovered that the curvature actually used by the lateral controllers was not logged anywhere. I added it temporarily, and was surprised to discover that the output of get_lag_adjusted_curvature was in part responsible for the delayed and jerky steering.
> Add desired curvatures to controlsState

- car.capnp
Per DM discussion with @adeebshihadeh, begin renaming FAW to Hongqi in service of the in-progress Hongqi HS5 port. The FAW parent company owns and manufactures many other brands which aren't necessarily going to be Hongqi compatible.
While here, marking the Stellantis safety ID as free for recycling. I added this for an earlier version of the Ram port, but it ended up making sense to consolidate it with Chrysler.
> Panda safety ID list cleanup

- car.capnp
- log.capnp
We can also make a new state, but it's unclear what takes precedence (long or lat overriding)
> Add fields for lateral override

- log.capnp
add qcom as ephemerisSourceType
> add qcom ephemerisSourceType

- messaging/messaging.h
Fixes compile error with clang version 14.0.6.
```
scons: *** [selfdrive/boardd/can_list_to_can_capnp.o] Error 1
In file included from selfdrive/loggerd/bootlog.cc:4:
./cereal/messaging/messaging.h:102:19: error: use of undeclared identifier 'CLOCK_BOOTTIME'
clock_gettime(CLOCK_BOOTTIME, &t);
^
```
> Add missing time.h include

- car.capnp
Allocate safety mode for certain last-gen [Volkswagen MLB](https://en.wikipedia.org/wiki/Volkswagen_Group_MLB_platform) that don't have FlexRay.
> VW MLB: Add safety mode

- car.capnp
replaces never used `vcu` added for hyundai before we switched to the camera with `hvac`
> Ecu: add hvac

- car.capnp
So we can know without any assumptions whether a request on bus 1 was made to the OBD port or not
> CarFw: add obdMultiplexing

- car.capnp
true if some ECU is faulted, but car remains controllable (for ex. camera faulted, but we are controlling both lat and long)
also for ex. camera faulted and we are not controlling long, that would be CRITICAL (accFaulted)
> carState: non-critical car faulted field

- car.capnp
We can, in the future, revive this to distinguish ABS module/brake controller related faults and PCM/accelerator control faults in the qlogs, but for now, Honda was the only make using this (for both brake and normal PCM ACC faults), so remove.
> Deprecate brakeUnavailable event

- messaging/messaging.cc
- messaging/messaging_pyx.pyx
This aims to make socket create/connect failures more descriptive. Currently the c++ op services and Pub/SubMasters usually fail with assertion or segfault, which does not provide any information about the reason (which may be trivial to solve).
This happens very often with ZMQ, when some other service on your local machine is using some 80XX port.
This is also alignment with cython wrappers which do throw an error when connect fails.
> connect: add error messages when Socket connect fails

- car.capnp
Originally added for: https://github.com/commaai/openpilot/pull/25606. This makes it a generic Ecu we can use for different brands, specifically for Toyota here: https://github.com/commaai/openpilot/pull/28628.
Needs openpilot PR: https://github.com/commaai/openpilot/pull/28629
- Some info about the Chrysler HCP: https://www.allpar.com/threads/deep-inside-the-chrysler-pacifica-hybrid-system.230025/
Summary: HCP has (is part of) an inverter and controls flow of energy and the motors.
- Some info about Toyota's hybrid system: https://en.wikipedia.org/wiki/Hybrid_Synergy_Drive
Summary: Toyota also has a computer/ECU that manages the power flow between engine, MG2 (motor generator), and battery.
- Honda is similar with the [Integrated Motor …
> CarParams.Ecu: rename hcp to hybrid

- visionipc/visionbuf_ion.cc
remove ion_init(), refactor ion_fd to struct IonFileHandle to fix 2 issues:
1. `ion_init()` is not thread safe, ion_fd may be opened multiple times.  ( `allocate` can be called in multiple threads, e.g. v4l_encoder), This may cause the client to use a different ion_fd for subsequent ioctl than the one used for ION_IOC_ALLOC 
2. ion_fd not closed on exit.
> Visionbuf: refactor ion_fd to struct IonFileHandle

- messaging/impl_zmq.cc
- messaging/impl_zmq.h
ZMQ pub sockets cannot be shared between processes, and its behavior is undefined when they are.
Connected with: https://github.com/commaai/openpilot/pull/30115
> zmq: assert the same PID

- car.capnp
- log.capnp
> deprecate curvature steer control type

- visionipc/visionipc_server.cc
Reverts commaai/cereal#580
this breaks cabana as is
> Revert "move vipc to a prefix folder"

- car.capnp
I'm in the process of reverse engineering the Vauxhall/Opel Corsa F, and it looks as though the LKAS hardware is shared between Citroën/Peugot/DS/Opel. Although PSA Group is now merged with Stellantis, I think this is the best way to group these potential platforms in openpilot.
The platfrom is called [CMP (or EMP1)](https://en.wikipedia.org/wiki/Common_Modular_Platform#CMP).
> PSA: add safety mode

- log.capnp
addresses the `add bootlog id to initData` requirement for logging more boot info
Related to https://github.com/commaai/openpilot/pull/32293
> add bootlogId to `initData`

- .github/workflows/tests.yml
- Dockerfile
- msgq/tests/test_fake.py
- msgq/tests/test_messaging.py
- msgq/tests/test_poller.py
- msgq/visionipc/tests/test_visionipc.py
- pyproject.toml
Part of https://github.com/commaai/openpilot/issues/32941
> Convert tests to pytests

- Dockerfile
now you can import anything from msgq regardless of where you are inside the docker container
discovered while making opendbc a package https://github.com/commaai/opendbc/pull/1069, pytest would fail on importing a file
> fix PYTHONPATH

- msgq/impl_zmq.cc
resolve https://github.com/commaai/openpilot/issues/34031 :
>  the issue is caused by a port mismatch between the Mac and the device:
> 
>     Attempting to connect to zmq endpoint: tcp://172.16.0.20:60942
>     Expected port on the device: 63557
> 
> It seems the static int get_port(std::string endpoint) function returns different port values on macOS and Linux, likely due to platform differences in how std::hash behaves.
This pr fixes the issue where the `get_port` function returns different port values on macOS and Linux due to platform-specific behavior of `std::hash`. The mismatch in port values causes connection failures in ZMQ. The solution replaces` std::hash `with a custom FNV-1a hash function to ensure consistent port values across platforms, and reducing the risk of collisions.
> Refactor get_port to use FNV-1a hash for consistency across platforms

- msgq/visionipc/visionipc_client.cc
Fixes a ui crash in openpilot when ignition is rapidly cycled from off to on to off. The first assertion always passes (due to timing?), but the second can sometimes return -1.
This return code comes from this line where the errno is always 104 (ECONNRESET):
https://github.com/commaai/msgq/blob/434ed2312c980b5504a4a75001d04c3ecbddf93f/msgq/visionipc/visionipc.cc#L92-L93
> VisionIpc: fix exception if server is killed while client is getting streams

- SConscript
- msgq/impl_msgq.cc
- msgq/ipc.pxd
- msgq/ipc_pyx.pyx
- msgq/tests/test_messaging.py
Replaced the previous method of installing, saving, and restoring signal handlers with a more streamlined and standard approach using signal masks (**pthread_sigmask**, **sigtimedwait**) for blocking receive operations. This update enhances the consistency and reliability of signal handling, aligning with best practices. It also removes the need for `msgq_poll`, thereby improving the efficiency of the receive function.
Additionally, a new test case, `test_receive_interrupts_on_sigint`, has been added to confirm and verify the functionality of the updated signal handling.
Since signal blocking is now managed in the C++ code, `nogil` is used in the Cython code to ensure the GIL is released during the execution of the receive function. This prevents it from impacting other Python threads.
> msgq: refactor blocking recv for improved robustness and performance

- msgq/impl_msgq.cc
- msgq/ipc_pyx.pyx
The only difference when receiving a termination signal is this line not being ran, but the program would be exiting anyway if this is the case:
```
msgq_msg_close(&msg); // Free unused message on exit
```
With the handler, the polling is not interrupted, so we hang until the timeout is up. If this is set high, we can get stuck here on exit.
> remove receive signal handler

- msgq/ipc.pxd
- msgq/ipc_pyx.pyx
Add `with nogil` blocks to release the GIL during c++ operations, allowing better concurrency in multi-threaded scenarios.
> Add 'with nogil' to SubSocket for GIL-Free C++ operations
